export { default as Settings } from "./Settings";
export { default as Authorization } from "./Authorization";
export { default as Home } from "./Home";
export { default as Playlist } from "./Playlist";
export { default as Account } from "./Account";
export { default as Search } from "./Search";
export { default as Library } from "./Library";
export { default as Category } from "./Category";
export { default as User } from "./User";
